global._ = require( "lodash" );
global.when = require( "when" );
var chai = require( "chai" );
chai.use( require( "chai-as-promised" ) );
global.should = chai.should();
global.expect = chai.expect;
global.fs = require( "fs" );
global.path = require( "path" );
global.sinon = require( "sinon" );
chai.use( require( "sinon-chai" ) );
require( "sinon-as-promised" );
global.proxyquire = require( "proxyquire" );
